# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'F:\Yroroki\Pyтон\generator_w_design\generate_dm.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
import os.path

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(306, 372)
        Form.setStyleSheet("QWidget{\n"
"background-color:#380438;\n"
"}\n"
"QLineEdit{\n"
"background-color: #B10361;\n"
"border: 4px solid black;\n"
"}\n"
"#pushButton{\n"
"font-family:Regular;\n"
"font-size:60px;\n"
"color:#C96161;\n"
"text-align:center;\n"
"padding-bottom:5px;\n"
"background-color: #FF7272;\n"
"border-radius:15px;\n"
"}\n"
"#pushButton:pressed{\n"
"background-color: #C15F5F;\n"
"color:#EA7878;\n"
"}")
        self.pushButton = QtWidgets.QPushButton(Form)
        self.pushButton.setGeometry(QtCore.QRect(80, 300, 141, 61))
        self.pushButton.setIconSize(QtCore.QSize(110, 50))
        self.pushButton.setAutoRepeat(False)
        self.pushButton.setAutoExclusive(False)
        self.pushButton.setAutoDefault(False)
        self.pushButton.setDefault(False)
        self.pushButton.setFlat(False)
        self.pushButton.setObjectName("pushButton")
        self.lineEdit = QtWidgets.QLineEdit(Form)
        self.lineEdit.setGeometry(QtCore.QRect(20, 140, 261, 31))
        self.lineEdit.setInputMask("")
        self.lineEdit.setText("")
        self.lineEdit.setFrame(False)
        self.lineEdit.setCursorPosition(0)
        self.lineEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(Form)
        self.lineEdit_2.setGeometry(QtCore.QRect(20, 180, 261, 31))
        self.lineEdit_2.setText("")
        self.lineEdit_2.setFrame(False)
        self.lineEdit_2.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.lineEdit_3 = QtWidgets.QLineEdit(Form)
        self.lineEdit_3.setGeometry(QtCore.QRect(20, 220, 261, 31))
        self.lineEdit_3.setText("")
        self.lineEdit_3.setFrame(False)
        self.lineEdit_3.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.lineEdit_4 = QtWidgets.QLineEdit(Form)
        self.lineEdit_4.setGeometry(QtCore.QRect(20, 260, 261, 31))
        self.lineEdit_4.setText("")
        self.lineEdit_4.setFrame(False)
        self.lineEdit_4.setCursorPosition(0)
        self.lineEdit_4.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(110, 30, 81, 81))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap(":/newPrefix/github-markw0x.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.pushButton.setText(_translate("Form", ".md"))
        self.lineEdit.setPlaceholderText(_translate("Form", "Name"))
        self.lineEdit_2.setPlaceholderText(_translate("Form", "Link"))
        self.lineEdit_3.setPlaceholderText(_translate("Form", "Code"))
        self.lineEdit_4.setPlaceholderText(_translate("Form", "File"))
import resource_rc



if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
